### ISSUE TITLE
"We are sorry" on Keycloak after adding new OAuth2 on Swagger UI

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/pmo#67]
<img width="933" alt="image" src="https://github.com/tracehubpm/pmo/assets/83453843/4f1faa36-614c-4515-a599-31b62566afb1">

right after this form submitted, I got redirected to "We are sorry" on a Keycloak:

<img width="1393" alt="image" src="https://github.com/tracehubpm/pmo/assets/83453843/d866741c-362e-4e6b-a9d6-1410c0223350">

**Comment by h1alexbel** [comment]
@hizmailovich take a look, please

**Comment by hizmailovich** [comment]
@h1alexbel 
Take a look at `Authorization URL` and `Token URL`. The host should be `keycloak`, not `localhost`, that's why Swagger can't connect to the Keylock.
I suppose, you have the incorrect `.env` file, I will send you a new version.

**Comment by hizmailovich** [comment]
@h1alexbel 
On Swagger UI you need to provide `client id` and `client secret` of the current client (it's our app, not an identity provider), however according to your screenshot you are using the client id of github identity provider.
So, I will add these creds to our `.env` file too, I will send you a new version.

**Comment by hizmailovich** [comment]
By the way, I fixed some invalid configurations in Keycloak that can affect Swagger

**Comment by hizmailovich** [comment]
![image](https://github.com/tracehubpm/pmo/assets/70943235/8c66dd4e-bc5c-49ad-995a-bf8bf39b8055)
