### ISSUE TITLE
Can be replaced with ResponseStatusException

### ISSUE THREAD

**Issue by l3r8yJ** [tracehubpm/pmo#80]
More convenient way is [RSE](https://www.baeldung.com/spring-response-status-exception#responsestatusexception). It would be automatically handled by Spring 

https://github.com/tracehubpm/pmo/blob/6ba5195fb667ab6beb67af340942bcd67699c469/src/main/java/git/tracehub/pmo/exception/ResourceAlreadyExistsException.java#L32

https://github.com/tracehubpm/pmo/blob/6ba5195fb667ab6beb67af340942bcd67699c469/src/main/java/git/tracehub/pmo/exception/ResourceNotFoundException.java#L32

Can be replaced with 

```java
public class SomeExcpetion extends ResponseStatusException { 
```

Response:
```bash
HTTP/1.1 404
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sat, 26 Dec 2020 19:38:09 GMT

{
    "timestamp": "2020-12-26T19:38:09.426+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/some/path"
}
```

**Comment by h1alexbel** [comment]
@l3r8yJ thanks for bug report, @hizmailovich take a look, please
